### ISSUE TITLE
Adding elements to the beginning/end of the zipper without changing focus

### ISSUE THREAD

**Issue by Kurren123** [turboMaCk/non-empty-list-alias#17]
Thank you for this library. I want the user to be able to view an element of the zipper, but at the same time new elements may be pushed onto the end of the zipper. Would it be possible to add something like `cons` or `append` which don't change the focus?

**Comment by turboMaCk** [comment]
It would be possible to add the function though it would most likely have linear complexity (depending on the number of previous or next items) so Zipper might not be the best data-structure if this is the operation you're primarily looking for.

Anyway it still might make sense to add it. Thanks for the input. I already have this messy issue with functions I would wish to have on Zipper as I'm using it. I'll add this one to the list https://github.com/turboMaCk/non-empty-list-alias/issues/16

**Comment by Kurren123** [comment]
@turboMaCk  Thanks for your quick reply. Apologies if I'm misunderstanding, but would `cons` be something like:

```elm
cons : a -> Zipper a -> Zipper a
cons a (Zipper prev current next) = 
    Zipper (a :: prev) current next
```

Which is not linear?

**Comment by turboMaCk** [comment]
yes indeed the previous list is in reverse order so the functions like `prev` are constant time.

This post on discorse has some additional explanations https://discourse.elm-lang.org/t/representing-nonempty-list-as-pair-a-list-a/5771/4?u=turbomack

Yes adding the information to the docs should be fine. That's being said if I would  consider defining zipper with `deck` instead of list if I would be in need of using these operations a lot. But it always depend on a context. Certainly linear is not that bad and it's fine to use linear operations (it doesn't even matter unless the length of the data is quite significant).

**Comment by Kurren123** [comment]
@turboMaCk Sounds good! at the moment I just need a `cons`, and I'm only holding up to 200 items. I'd be happy to give a PR a shot.

**Comment by Kurren123** [comment]
Shall we stick to calling it `cons` or call it `insertStart` to go with the theme that all `insertX` functions don't move focus?

**Comment by turboMaCk** [comment]
@Kurren123 yes I think we will need some other name (like `insertStart`). With naming I usually like to give it some time once thoughts settle but feel free to recommend names if you have some ideas.

**Comment by turboMaCk** [comment]
1.1.0 https://github.com/turboMaCk/non-empty-list-alias/releases/tag/1.1.0 includes `prepend` and `append` functions.
